on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: revdep-check

jobs:
  revdep-check:
    runs-on: ubuntu-latest

    name: ${{ matrix.package }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {package: mlr-org/bbotk, ref: rush_v1}
          - {package: mlr-org/mlr3tuning, ref: rush_v1}

    steps:
      - uses: actions/checkout@v3
        with:
          path: rush

      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.package }}
          ref: ${{ matrix.ref }}
          path: revdep-pkg

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - uses: supercharge/redis-github-action@1.8.1
        with:
          redis-version: 7

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: revdep-pkg

      - name: Install rush from source
        run: R CMD INSTALL rush
        shell: bash

      - uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual")'
          working-directory: revdep-pkg
